In [1]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
b=np.array([[2,2,0],[1,0,1],[0,1,0]])
print(a)
print(b)

[[1 0 2]
 [2 1 1]
 [3 0 3]]
[[2 2 0]
 [1 0 1]
 [0 1 0]]


In [24]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
b=np.array([[2,2,0],[1,0,1],[0,1,0]])
print(a)
print(b)
a.flags

[[1 0 2]
 [2 1 1]
 [3 0 3]]
[[2 2 0]
 [1 0 1]
 [0 1 0]]


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [44]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
b=np.array([[2,2,0],[1,0,1],])
b.shape
a.shape

(3, 3)

In [50]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.strides

(12, 4)

In [52]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.ndim

2

In [54]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.data

In [56]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.size

9

In [58]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.itemsize

4

In [60]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.base

In [62]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.nbytes

36

In [64]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.T

array([[1, 2, 3],
       [0, 1, 0],
       [2, 1, 3]])

In [66]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.real

array([[1, 0, 2],
       [2, 1, 1],
       [3, 0, 3]])

In [69]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])