In [1]:
import numpy as np 
array = np.array([1,2,3])
print(array)


[1 2 3]


In [3]:
import numpy as np
array = np.ones((6,5))
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
import numpy as np 
array = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(array)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [14]:
import numpy as np 
array = np.identity(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
import numpy as np 
array = np.full((2,3),3)
print(array)

[[3 3 3]
 [3 3 3]]


In [18]:
import numpy as np 
array = np.full((2,3),7)
print(array)

[[7 7 7]
 [7 7 7]]


In [20]:
import numpy as np 
array = np.identity(7)
print(array[2:5,0:3])

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
import numpy as np 
array = np.identity(7)
print(array[:,:])

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [24]:
import numpy as np 
array = np.identity(7)
print(array)
print(array[-3:-1,3:-1])

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]]
